_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.19.6
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 32
dataset:
    value: Chiranjeev007/STL-10_Subset
epochs:
    value: 1
learning_rate:
    value: 0.0001
model:
    value: resnet18-pretrained
weight_decay:
    value: 0.0001
